// SPDX-License-Identifier: MIT
pragma solidity ^0.8.25;

import {
    AccessControlDefaultAdminRules
} from "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol";
import {IUTXOSettlementVerifier} from "../interfaces/IUTXOSettlementVerifier.sol";
import {IGroth16Verifier} from "../interfaces/IGroth16Verifier.sol";
import {ZeroAddress} from "@interop-lib/libraries/errors/CommonErrors.sol";

/// @title Groth16SettlementVerifier
/// @notice Groth16 proof verifier for UTXO settlement intents.
/// @dev Implements IUTXOSettlementVerifier by delegating to the UTXOVerifier contract
///      generated by snarkjs from the UTXOSettlement circuit (13 public signals).
///
///      Proof encoding (abi.encode of proof + signals, passed as `proof` bytes):
///        uint256[2]    a       — G1 point pi_a
///        uint256[2][2] b       — G2 point pi_b (snarkjs coordinate order)
///        uint256[2]    c       — G1 point pi_c
///        uint256[13]   signals — public signals in canonical circuit order
///
///      Signal mapping for settlement (non-pool) use:
///        [0]  merkleRoot       = uint256(intentId)  — binds proof to this intent
///        [1]  chainId          = block.chainid
///        [2]  dstChainId       = block.chainid       — same-chain settlement
///        [3]  protocolEpoch    = 0
///        [4]  fee              = 0
///        [5]  relayer          = 0
///        [6]  nullifier[0]     = uint256(intentId)  — reuse intentId as nullifier
///        [7]  nullifier[1]     = 0
///        [8]  outCommitment[0] = 0
///        [9]  outCommitment[1] = 0
///        [10] withdrawOwner    = uint160(account)
///        [11] withdrawRecipient = uint160(account)
///        [12] withdrawAmount   = amount
contract Groth16SettlementVerifier is IUTXOSettlementVerifier, AccessControlDefaultAdminRules {
    uint48 public constant DEFAULT_ADMIN_DELAY = 1 days;

    event VerifierContractUpdated(address indexed verifierContract);

    IGroth16Verifier public verifierContract;

    constructor(address initialAdmin)
        AccessControlDefaultAdminRules(DEFAULT_ADMIN_DELAY, initialAdmin)
    {
        if (initialAdmin == address(0)) revert ZeroAddress();
    }

    function setVerifierContract(address verifierContract_) external onlyRole(DEFAULT_ADMIN_ROLE) {
        if (verifierContract_ == address(0)) revert ZeroAddress();
        if (verifierContract_.code.length == 0) revert ZeroAddress();
        verifierContract = IGroth16Verifier(verifierContract_);
        emit VerifierContractUpdated(verifierContract_);
    }

    /// @inheritdoc IUTXOSettlementVerifier
    function verifySettlement(
        bytes32 intentId,
        address settlementModule,
        address account,
        uint256 amount,
        bool isMint,
        bytes calldata proof
    ) external view override returns (bool) {
        if (intentId == bytes32(0) || settlementModule == address(0) || account == address(0) || amount == 0) {
            return false;
        }

        IGroth16Verifier v = verifierContract;
        if (address(v) == address(0)) return false;

        (
            uint256[2] memory a,
            uint256[2][2] memory b,
            uint256[2] memory c,
            uint256[13] memory signals
        ) = abi.decode(proof, (uint256[2], uint256[2][2], uint256[2], uint256[13]));

        // Verify public signals match settlement parameters.
        if (signals[0] != uint256(intentId)) return false;
        if (signals[10] != uint256(uint160(account))) return false;
        if (signals[11] != uint256(uint160(account))) return false;
        if (signals[12] != amount) return false;
        // isMint direction is enforced by the circuit's note commitment — not a separate signal.
        // Suppress unused parameter warning.
        isMint;

        return v.verifyProof(a, b, c, signals);
    }
}
