name: Secrets Scan

on:
  pull_request:
  push:
    branches:
      - main

      - dev
  workflow_dispatch:

jobs:
  gitleaks:
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/_reusable-secrets-scan.yml
